[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
logfile=/dev/null
loglevel=error
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:xvfb]
command=/usr/bin/Xvfb :%(ENV_DISPLAY_NUM)s -screen 0 1920x1080x24
autostart=true
autorestart=true
priority=10

[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY=":%(ENV_DISPLAY_NUM)s"
autostart=true
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -forever -display :%(ENV_DISPLAY_NUM)s -nopw -shared
autostart=true
autorestart=true

[program:novnc]
command=/opt/novnc/utils/novnc_proxy --vnc localhost:5900 --listen %(ENV_NOVNC_PORT)s --web /opt/novnc
directory=/opt/novnc
autostart=true
autorestart=true


[program:pythonapp]
command=/bin/bash -c "python3 /app/Codigo/main.py || true; sleep 2; supervisorctl shutdown || true"
environment=DISPLAY=":%(ENV_DISPLAY_NUM)s"
directory=/app
autostart=true	
autorestart=false
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0